CREATE TABLE comment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id        BIGINT,
    data           TIMESTAMP WITHOUT TIME ZONE,
    text           VARCHAR(255),
    commentator_id BIGINT,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_COMMENTATOR FOREIGN KEY (commentator_id) REFERENCES "user" (id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

UPDATE "user"
SET email = 'n/a'
WHERE email IS NULL;
ALTER TABLE "user"
    ALTER COLUMN email SET NOT NULL;